name    'enovance-ceph'
version '1.0.0'
source 'git://github.com/enovance/puppet-ceph.git'
author 'François Charlier <francois.charlier@enovance.com>'
license 'AGPLv3'
summary 'A puppet module to install & configure Ceph'
description 'A puppet module to install & configure Ceph'
project_page 'https://github.com/enovance/puppet-ceph'

dependency 'puppetlabs/apt', '>= 1.1.0'
dependency 'puppetlabs/concat', '>= 0.2.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
